services:
  php:
    build: './php/'
    volumes:
      - ./public:/var/www/html/
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Initially creates employees table
      - ./public/dump:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: "passwd"
      MYSQL_DATABASE: "mydb"
      MYSQL_USER: "user1"
      MYSQL_PASSWORD: "passwd"
  db_backup:
    image: mysql:latest
    container_name: db_backup
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=passwd
    volumes:
      - ./backups:/backups
    command: >
      /bin/bash -c "
      while true; do
        TIMESTAMP=$(date +%Y%m%d_%H%M%S)
        mysqldump -h mysql -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE > /backups/backup_$TIMESTAMP.sql;
        echo 'Backup created at '$TIMESTAMP;
        sleep 120;
      done"
    depends_on:
      - mysql
volumes:
    db_data:


